// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thuctap01.Models;

namespace Thuctap01.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20221030135000_THUCTAP")]
    partial class THUCTAP
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Thuctap01.Models.DangnhapModel", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Chucdanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("DangnhapModels");
                });

            modelBuilder.Entity("Thuctap01.Models.GiangvienModel", b =>
                {
                    b.Property<int>("Magiangvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BHXH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Chucvu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gioitinh")
                        .HasColumnType("int");

                    b.Property<string>("Hovaten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayapdungchucvu")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngaybatdaulamviec")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngaycap")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Noicap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoCMND")
                        .HasColumnType("int");

                    b.Property<string>("Tobomon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Trinhdodaotao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vanbanquyetdinh")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Magiangvien");

                    b.ToTable("GiangvienModels");
                });

            modelBuilder.Entity("Thuctap01.Models.Luong", b =>
                {
                    b.Property<string>("Loaihopdong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bacluong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Filedinhkem")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Hesoluong")
                        .HasColumnType("int");

                    b.Property<int>("Luongcoban")
                        .HasColumnType("int");

                    b.Property<int>("Lươngcoban")
                        .HasColumnType("int");

                    b.Property<string>("Ngachhang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Ngayapdungngachbac")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Vanbanquyetdinh")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("baohiemphaidong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Loaihopdong");

                    b.ToTable("Luongs");
                });

            modelBuilder.Entity("Thuctap01.Models.MuchocphiModel", b =>
                {
                    b.Property<int>("Mamonhoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Donvitinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Khoakhoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Monhoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<double>("Tonghocphi")
                        .HasColumnType("float");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("mucthu")
                        .HasColumnType("int");

                    b.Property<double>("nienkhoa")
                        .HasColumnType("float");

                    b.HasKey("Mamonhoc");

                    b.ToTable("MuchocphiModels");
                });

            modelBuilder.Entity("Thuctap01.Models.QuanlyhocphiModel", b =>
                {
                    b.Property<int>("Mahocvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Doituong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Hocphi")
                        .HasColumnType("float");

                    b.Property<string>("Khoakhoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayNhapHoc")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngaythu")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Tenhocvien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Thucthu")
                        .HasColumnType("float");

                    b.Property<double>("Tonghocphi")
                        .HasColumnType("float");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Mahocvien");

                    b.ToTable("QuanyhocphiModelss");
                });
#pragma warning restore 612, 618
        }
    }
}
